QUIC/SCION protocol version
Anapaya/quic-go pull request #1
Opened 2022-06-22 11:42 UTC by sustrik

1. Introduction of the new version number
2. Outgoing packets are not padded, making them smaller
3. Incoming packets are not being dropped because of being too small
4. MTU discovery starts at 600B instead of 1200B

2022-06-22 12:02 UTC, oncilla requested changes
> Reviewed 4 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/quic-go/1)* status: 4 of 53 files reviewed, 3 unresolved discussions (waiting on @oncilla and @sustrik)

*[a discussion](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AEMWgBkOLm-OH8loQ:-N5AEMWh-LjcHQ-O5zFD:boticxu) (no related file):*
I don't think we should commit the WORKSPACE and/or bazel files.
AFAIK, rules_go changes the behavior based on whether the repository is bazel enabled or not.

This patch should really be the minimal possible patch, such that applying it on top of other tags leads to as little conflicts as possible.
By committing the build files, we will need to regenerate them and we need to maintain the registered go sdk version, rules_go version, and gazelle version.

For easier development, we can create a helper tool that copies over the WORKSPACE and a basic BUILD file.

___
___
*[`packet_packer.go` line 361 at r1](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AHVc086iHLXw_peJX:-N5AHVc11jv6yVgkdH9a:b-vf58xo) ([raw file](https://github.com/anapaya/quic-go/blob/775ce8d481c0622706c0f9412b80c5bce5bdbfa1/packet_packer.go#L361)):*
> ```Go
> func (p *packetPacker) initialPaddingLen(frames []ackhandler.Frame, size protocol.ByteCount) protocol.ByteCount {
> 	// With QUIC/SCION protocol, no padding is added.
> 	if protocol.IsSCIONVersion(p.version) {
> ```

Do we not need to pad up to 600 still to uphold the contract?
___
*[`server.go` line 354 at r1](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AFwXECVT3HMxw3xFN:-N5AFwXECVT3HMxw3xFO:bga8aic) ([raw file](https://github.com/anapaya/quic-go/blob/775ce8d481c0622706c0f9412b80c5bce5bdbfa1/server.go#L354)):*
> ```Go
> 	}
> 	if hdr.Type == protocol.PacketTypeInitial {
> 		if !protocol.IsSCIONVersion(hdr.Version) && p.Size() < protocol.MinInitialPacketSize {
> ```

This disables the min size check completely. 
AFAICT, we agreed to have 600 min initial packet size.


<!-- Sent from Reviewable.io -->

2022-06-22 13:12 UTC, sustrik reviewed
> *[Reviewable](https://reviewable.io/reviews/anapaya/quic-go/1)* status: 2 of 53 files reviewed, 3 unresolved discussions (waiting on @oncilla)

*[a discussion](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AEMWgBkOLm-OH8loQ:-N5AXidM1Qp6vabMwMIA:b-896fix) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I don't think we should commit the WORKSPACE and/or bazel files.
AFAIK, rules_go changes the behavior based on whether the repository is bazel enabled or not.

This patch should really be the minimal possible patch, such that applying it on top of other tags leads to as little conflicts as possible.
By committing the build files, we will need to regenerate them and we need to maintain the registered go sdk version, rules_go version, and gazelle version.

For easier development, we can create a helper tool that copies over the WORKSPACE and a basic BUILD file.





</blockquote></details>

Done.

___
___
*[`packet_packer.go` line 361 at r1](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AHVc086iHLXw_peJX:-N5AXk4GEJ7acV3fWfmJ:b-896fix) ([raw file](https://github.com/anapaya/quic-go/blob/775ce8d481c0622706c0f9412b80c5bce5bdbfa1/packet_packer.go#L361)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Do we not need to pad up to 600 still to uphold the contract?
</blockquote></details>

Done.
___
*[`server.go` line 354 at r1](https://reviewable.io/reviews/anapaya/quic-go/1#-N5AFwXECVT3HMxw3xFN:-N5AXbOg-6G50RpTMx9M:b-896fix) ([raw file](https://github.com/anapaya/quic-go/blob/775ce8d481c0622706c0f9412b80c5bce5bdbfa1/server.go#L354)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This disables the min size check completely. 
AFAICT, we agreed to have 600 min initial packet size.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-27 04:32 UTC, oncilla reviewed
> Reviewed 51 of 51 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anapaya/quic-go/1)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2022-06-27 04:32 UTC, oncilla approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/anapaya/quic-go/1#-:-N5YQcOc72pr4vKSTe3T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)



<!-- Sent from Reviewable.io -->

2022-06-27 04:32 UTC, oncilla approved these changes
> *[Reviewable](https://reviewable.io/reviews/anapaya/quic-go/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sustrik)



<!-- Sent from Reviewable.io -->

2022-06-27 05:23 UTC, merged